server:
  port: 8001
spring:  application:    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.110.144:3306/cloud?useSSL=false&serverTimezone=UTC
    username: root
    password: Root@123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #Number of physical connections established during initialization
      initial-size: 5
      #Minimum number of connection pools
      min-idle: 5
      #Maximum number of connection pools
      max-active: 20
      #Maximum wait time when getting a connection
      max-wait: 60000
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*/*.xml