server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 100.10.10.206:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'


 
 
