server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: default
    nacos:
      discovery:
        server-addr: 100.10.10.206:8847,100.10.10.206:8848,100.10.10.206:8849
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.10.10.206:3306/seata_order?useSSL=false&serverTimezone=UTC
    username: root
    password: root@123
feign:
  hystrix:
    enabled: false
mybatis-plus:
  mapper-locations:    - classpath:mapper/*.xml
  #打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl